
### 获取数据库中所有数据
GET  http://localhost:3000/db

### 获取指定数据库中所有数据
GET  http://localhost:3000/db?db=db1

### 获取指定数据库中指定表数据
GET  http://localhost:3000/posts?db=db1

###
GET  http://localhost:3000/posts?db=db2

### 获取所有数据库列表
GET  http://localhost:3000/databases

### 新增表
POST  http://localhost:3000/addTable?db=db1
Content-Type: application/json

{ 
    "tableName": "order", 
    "data": [
      { "id": 1, "name": "Order 1" },
      { "id": 2, "name": "Order 2" }
    ]
}

### 新增表数据
POST  http://localhost:3000/posts?db=db1
Content-Type: application/json

{ 
    "title": "json-server",
    "author": "typicode"
}

### 批量新增表数据
POST  http://localhost:3000/add/batch?db=db1
Content-Type: application/json

[{ 
    "title": "json-server",
    "author": "typicode"
},
{ 
    "title": "json-server2",
    "author": "typicode2"
}]