
### 获取数据库中所有数据
GET  http://localhost:3000/db

### 获取指定数据库中所有数据
GET  http://localhost:3000/db?db=db1

### 获取指定数据库中指定表数据
GET  http://localhost:3000/posts?db=db1

###
GET  http://localhost:3000/posts?db=db2

### 获取所有数据库列表
GET  http://localhost:3000/databases

### 新增表
POST  http://localhost:3000/addTable?db=db1
Content-Type: application/json

{ 
    "tableName": "order", 
    "data": [
      { "id": 1, "name": "Order 1" },
      { "id": 2, "name": "Order 2" }
    ]
}

### 新增表数据
POST  http://localhost:3000/user
Content-Type: application/json

{ 
    "title": "json-server",
    "author": "typicode"
}

### 批量新增表数据
POST  http://localhost:3000/add/batch?db=db1
Content-Type: application/json

[{ 
    "title": "json-server",
    "author": "typicode"
},
{ 
    "title": "json-server2",
    "author": "typicode2"
}]

### 删除表
DELETE  http://localhost:3000/tables/tab


### 删除表数据
DELETE  http://localhost:3000/user/10


### 修改表数据
PUT  http://localhost:3000/user/15
Content-Type: application/json

{
    "name": "Linda Brown2",
    "str": "经热强之些。装放。称况。又政。2"
}

### 获取数据并携带关联的数据
GET  http://localhost:3000/user?_embed=car&db=default